// backend/src/seeds/eventsData.js
const demoEvents = [
  // 🌟 JANUARY
  {
    title: "New Year's Day",
    organisation: "Global",
    industry: "General Celebration",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 1, month: "January", year: 2025 },
  },
  {
    title: "World Introvert Day",
    organisation: "Global",
    industry: "Psychology & Awareness",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 2, month: "January", year: 2025 },
  },
  {
    title: "Prithivi Jayanti (Unity Day)",
    organisation: "Government of Nepal",
    industry: "National Days",
    eventType: "National Days",
    repeatsYearly: true,
    date: { day: 11, month: "January", year: 2025 },
  },
  {
    title: "National Youth Day (Nepal)",
    organisation: "Government of Nepal",
    industry: "Youth & Development",
    eventType: "National Days",
    repeatsYearly: true,
    date: { day: 12, month: "January", year: 2025 },
  },
  {
    title: "Maghe Sankranti",
    organisation: "Nepal",
    industry: "Cultural/Festival",
    eventType: "Nepali Festivals",
    repeatsYearly: true,
    date: { day: 13, month: "January", year: 2025 },
  },
  {
    title: "Basanta Panchami / Saraswati Puja",
    organisation: "Nepal",
    industry: "Education & Religion",
    eventType: "Nepali Festivals",
    repeatsYearly: true,
    date: { day: 22, month: "January", year: 2025 },
  },
  {
    title: "International Day of Education",
    organisation: "UN",
    industry: "Education",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 24, month: "January", year: 2025 },
  },
  {
    title: "International Day for the Total Elimination of Nuclear Weapons",
    organisation: "UN",
    industry: "Peace and Disarmament Sector",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 26, month: "January", year: 2025 },
  },
  {
    title: "International Day of Commemoration in Memory of the Victims of the Holocaust",
    organisation: "UN",
    industry: "Education, Human Rights, Peace & Cultural Heritage",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 27, month: "January", year: 2025 },
  },
  {
    title: "Martyrs' Day / Sahid Diwas",
    organisation: "Government of Nepal",
    industry: "National Days",
    eventType: "National Days",
    repeatsYearly: true,
    date: { day: 29, month: "January", year: 2025 },
  },
  {
    title: "Sonam Lhosar (Tamang New Year)",
    organisation: "Nepal",
    industry: "Cultural/Festival",
    eventType: "Nepali Festivals",
    repeatsYearly: true,
    date: { day: 30, month: "January", year: 2025 },
  },

  // 💕 FEBRUARY
  {
    title: "National Democracy Day (Nepal)",
    organisation: "Government of Nepal",
    industry: "National Holiday",
    eventType: "National Days",
    repeatsYearly: true,
    date: { day: 1, month: "February", year: 2025 },
  },
  {
    title: "World Cancer Day",
    organisation: "UN",
    industry: "Healthcare",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 4, month: "February", year: 2025 },
  },
  {
    title: "World Pulses Day",
    organisation: "UN",
    industry: "Agriculture and Food Security",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 10, month: "February", year: 2025 },
  },
  {
    title: "International Day of Women and Girls in Science",
    organisation: "UN",
    industry: "STEM and Gender Equality",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 11, month: "February", year: 2025 },
  },
  {
    title: "World Radio Day",
    organisation: "UN",
    industry: "Media and Communication",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 13, month: "February", year: 2025 },
  },
  {
    title: "Valentine's Day",
    organisation: "Global",
    industry: "Social & Cultural",
    eventType: "Holiday",
    repeatsYearly: true,
    date: { day: 14, month: "February", year: 2025 },
  },
  {
    title: "Democracy Day (Nepal)",
    organisation: "Government of Nepal",
    industry: "National Event",
    eventType: "National Days",
    repeatsYearly: true,
    date: { day: 19, month: "February", year: 2025 },
  },

  // 🌸 MARCH
  {
    title: "World Seagrass Day",
    organisation: "UN",
    industry: "Environment & Marine Ecology",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 1, month: "March", year: 2025 },
  },
  {
    title: "Zero Discrimination Day",
    organisation: "UN",
    industry: "Human Rights & Equality",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 1, month: "March", year: 2025 },
  },
  {
    title: "World Wildlife Day",
    organisation: "UN",
    industry: "Environment, Ecology & Conservation",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 3, month: "March", year: 2025 },
  },
  {
    title: "International Day for Ear and Hearing Care",
    organisation: "UN",
    industry: "Health & Medical Awareness",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 3, month: "March", year: 2025 },
  },
  {
    title: "International Women's Day",
    organisation: "UN",
    industry: "Gender Equality & Women Empowerment",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 8, month: "March", year: 2025 },
  },
  {
    title: "International Day of Women Judges",
    organisation: "UN",
    industry: "Law & Gender Equality",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 10, month: "March", year: 2025 },
  },
  {
    title: "International Day to Combat Islamophobia",
    organisation: "UN",
    industry: "Human Rights & Tolerance",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 15, month: "March", year: 2025 },
  },
  {
    title: "International Day of Happiness",
    organisation: "UN",
    industry: "Social Well-being & Mental Health",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 20, month: "March", year: 2025 },
  },
  {
    title: "International Day for the Elimination of Racial Discrimination",
    organisation: "UN",
    industry: "Human Rights & Anti-Discrimination",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 21, month: "March", year: 2025 },
  },
  {
    title: "World Poetry Day",
    organisation: "UN",
    industry: "Arts & Literature",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 21, month: "March", year: 2025 },
  },
  {
    title: "World Down Syndrome Day",
    organisation: "UN",
    industry: "Health & Disability Awareness",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 21, month: "March", year: 2025 },
  },
  {
    title: "International Day of Forests",
    organisation: "UN",
    industry: "Environment & Forestry",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 21, month: "March", year: 2025 },
  },
  {
    title: "International Nowruz Day",
    organisation: "UN",
    industry: "Culture & Heritage",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 21, month: "March", year: 2025 },
  },
  {
    title: "World Water Day",
    organisation: "UN",
    industry: "Environment & Water Resources",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 22, month: "March", year: 2025 },
  },
  {
    title: "World Meteorological Day",
    organisation: "UN",
    industry: "Science & Meteorology",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 23, month: "March", year: 2025 },
  },
  {
    title: "World Tuberculosis Day",
    organisation: "UN",
    industry: "Health & Disease Prevention",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 24, month: "March", year: 2025 },
  },
  {
    title: "Ghode Jatra (Kathmandu Valley)",
    organisation: "Nepal",
    industry: "Cultural",
    eventType: "Nepali Festivals",
    repeatsYearly: true,
    date: { day: 29, month: "March", year: 2025 },
  },

  // 🌷 APRIL
  {
    title: "World Autism Awareness Day",
    organisation: "UN",
    industry: "Health & Disability Awareness",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 2, month: "April", year: 2025 },
  },
  {
    title: "International Day for Mine Awareness and Assistance in Mine Action",
    organisation: "UN",
    industry: "Peace & Humanitarian Aid",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 4, month: "April", year: 2025 },
  },
  {
    title: "International Day of Sport for Development and Peace",
    organisation: "UN",
    industry: "Sports & Social Development",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 6, month: "April", year: 2025 },
  },
  {
    title: "World Health Day",
    organisation: "UN",
    industry: "Health & Medicine",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 7, month: "April", year: 2025 },
  },
  {
    title: "International Day of Human Space Flight",
    organisation: "UN",
    industry: "Science & Space Exploration",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 12, month: "April", year: 2025 },
  },
  {
    title: "Nepali New Year (Baisakh 1)",
    organisation: "Government of Nepal",
    industry: "National / Cultural",
    eventType: "Nepali Festivals",
    repeatsYearly: true,
    date: { day: 14, month: "April", year: 2025 },
  },
  {
    title: "International Mother Earth Day",
    organisation: "UN",
    industry: "Environment & Sustainability",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 22, month: "April", year: 2025 },
  },
  {
    title: "World Book and Copyright Day",
    organisation: "UN",
    industry: "Education, Literature & Culture",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 23, month: "April", year: 2025 },
  },
  {
    title: "World Malaria Day",
    organisation: "UN",
    industry: "Health & Disease Prevention",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 25, month: "April", year: 2025 },
  },
  {
    title: "International Jazz Day",
    organisation: "UN",
    industry: "Arts & Music",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 30, month: "April", year: 2025 },
  },

  // 🌺 MAY
  {
    title: "Labour Day (International Workers' Day)",
    organisation: "International Labour Organization",
    industry: "National / Labour",
    eventType: "National Days",
    repeatsYearly: true,
    date: { day: 1, month: "May", year: 2025 },
  },
  {
    title: "World Press Freedom Day",
    organisation: "UN",
    industry: "Media & Communication",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 3, month: "May", year: 2025 },
  },
  {
    title: "International Day of Families",
    organisation: "UN",
    industry: "Social Welfare & Family",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 15, month: "May", year: 2025 },
  },
  {
    title: "International Day of Living Together in Peace",
    organisation: "UN",
    industry: "Peace & Social Harmony",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 16, month: "May", year: 2025 },
  },
  {
    title: "International Day of Light",
    organisation: "UN",
    industry: "Science & Technology",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 16, month: "May", year: 2025 },
  },
  {
    title: "World Telecommunication and Information Society Day",
    organisation: "UN",
    industry: "Technology & Communication",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 17, month: "May", year: 2025 },
  },
  {
    title: "World Bee Day",
    organisation: "UN",
    industry: "Environment & Biodiversity",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 20, month: "May", year: 2025 },
  },
  {
    title: "World Day for Cultural Diversity for Dialogue and Development",
    organisation: "UN",
    industry: "Culture & Society",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 21, month: "May", year: 2025 },
  },
  {
    title: "International Day for Biological Diversity",
    organisation: "UN",
    industry: "Environment & Biodiversity",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 22, month: "May", year: 2025 },
  },
  {
    title: "International Day of UN Peacekeepers",
    organisation: "UN",
    industry: "Peace & Security",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 29, month: "May", year: 2025 },
  },
  {
    title: "World No Tobacco Day",
    organisation: "UN",
    industry: "Health & Awareness",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 31, month: "May", year: 2025 },
  },

  // ☀️ JUNE
  {
    title: "Global Day of Parents",
    organisation: "UN",
    industry: "Social Welfare & Family",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 1, month: "June", year: 2025 },
  },
  {
    title: "World Bicycle Day",
    organisation: "UN",
    industry: "Health, Environment & Transport",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 3, month: "June", year: 2025 },
  },
  {
    title: "World Environment Day",
    organisation: "UN",
    industry: "Environment & Sustainability",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 5, month: "June", year: 2025 },
  },
  {
    title: "World Oceans Day",
    organisation: "UN",
    industry: "Environment & Marine Conservation",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 8, month: "June", year: 2025 },
  },
  {
    title: "World Day Against Child Labour",
    organisation: "UN",
    industry: "Human Rights & Child Protection",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 12, month: "June", year: 2025 },
  },
  {
    title: "World Blood Donor Day",
    organisation: "UN",
    industry: "Health & Medical Awareness",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 14, month: "June", year: 2025 },
  },
  {
    title: "World Refugee Day",
    organisation: "UN",
    industry: "Human Rights & Humanitarian",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 20, month: "June", year: 2025 },
  },
  {
    title: "International Day of Yoga",
    organisation: "UN",
    industry: "Health & Well-being",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 21, month: "June", year: 2025 },
  },
  {
    title: "International Day against Drug Abuse and Illicit Trafficking",
    organisation: "UN",
    industry: "Health & Law Enforcement",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 26, month: "June", year: 2025 },
  },

  // 🌞 JULY
  {
    title: "International Day of the World's Indigenous Peoples",
    organisation: "UN",
    industry: "Human Rights & Culture",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 9, month: "July", year: 2025 },
  },
  {
    title: "World Population Day",
    organisation: "UN",
    industry: "Social Development & Demographics",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 11, month: "July", year: 2025 },
  },
  {
    title: "International Youth Day",
    organisation: "UN",
    industry: "Youth Development & Education",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 12, month: "July", year: 2025 },
  },
  {
    title: "World Humanitarian Day",
    organisation: "UN",
    industry: "Humanitarian & Social Work",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 19, month: "July", year: 2025 },
  },
  {
    title: "International Day of Friendship",
    organisation: "UN",
    industry: "Social Harmony & Peace",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 30, month: "July", year: 2025 },
  },

  // 🌻 AUGUST
  {
    title: "International Day of the World's Indigenous Peoples",
    organisation: "UN",
    industry: "Human Rights & Culture",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 9, month: "August", year: 2025 },
  },
  {
    title: "International Youth Day",
    organisation: "UN",
    industry: "Youth Development & Education",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 12, month: "August", year: 2025 },
  },
  {
    title: "World Humanitarian Day",
    organisation: "UN",
    industry: "Humanitarian & Social Work",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 19, month: "August", year: 2025 },
  },

  // 🍂 SEPTEMBER
  {
    title: "International Day of Charity",
    organisation: "UN",
    industry: "Social Welfare & Philanthropy",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 5, month: "September", year: 2025 },
  },
  {
    title: "International Literacy Day",
    organisation: "UN",
    industry: "Education & Literacy",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 8, month: "September", year: 2025 },
  },
  {
    title: "Constitution / National Day",
    organisation: "Government of Nepal",
    industry: "National Days",
    eventType: "National Days",
    repeatsYearly: true,
    date: { day: 20, month: "September", year: 2025 },
  },
  {
    title: "World Tourism Day",
    organisation: "UN",
    industry: "Tourism & Culture",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 27, month: "September", year: 2025 },
  },

  // 🍂 OCTOBER
  {
    title: "International Day of Older Persons",
    organisation: "UN",
    industry: "Social Welfare & Elderly Rights",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 1, month: "October", year: 2025 },
  },
  {
    title: "International Day of Non-Violence",
    organisation: "UN",
    industry: "Peace & Social Harmony",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 2, month: "October", year: 2025 },
  },
  {
    title: "World Teachers' Day",
    organisation: "UN",
    industry: "Education & Teaching",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 5, month: "October", year: 2025 },
  },
  {
    title: "World Mental Health Day",
    organisation: "UN",
    industry: "Health & Mental Health",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 10, month: "October", year: 2025 },
  },
  {
    title: "World Food Day",
    organisation: "UN",
    industry: "Food Security & Agriculture",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 16, month: "October", year: 2025 },
  },

  // 🍁 NOVEMBER
  {
    title: "Universal Children's Day",
    organisation: "UN",
    industry: "Child Rights & Welfare",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 20, month: "November", year: 2025 },
  },

  // ❄️ DECEMBER
  {
    title: "World AIDS Day",
    organisation: "UN",
    industry: "Health & Disease Awareness",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 1, month: "December", year: 2025 },
  },
  {
    title: "International Day of Persons with Disabilities",
    organisation: "UN",
    industry: "Disability Rights & Awareness",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 3, month: "December", year: 2025 },
  },
  {
    title: "Human Rights Day",
    organisation: "UN",
    industry: "Human Rights & Social Justice",
    eventType: "International Days",
    repeatsYearly: true,
    date: { day: 10, month: "December", year: 2025 },
  },
  {
    title: "Christmas Day",
    organisation: "Global",
    industry: "Religious & Cultural",
    eventType: "Holiday",
    repeatsYearly: true,
    date: { day: 25, month: "December", year: 2025 },
  },

];

module.exports = demoEvents;